### ISSUE TITLE
Remote WSL displays battery level at 0% on Windows laptop

### ISSUE THREAD

**Issue by wrussell1999** [Njanderson/resmon#12]
When using Remote WSL, it shows the battery level as 0%. I imagine it may be difficult to actually get that data when inside WSL, so maybe hide it, if WSL detected.
![image](https://user-images.githubusercontent.com/34094921/60334341-33371180-9993-11e9-9439-8e85b5d9d0b1.png)

The extension runs on the host, so should work fine for SSH as that will report the statistics of the machine running your code, however I haven't had a chance to test it yet. Will try later!

Using a ThinkPad T480s running Windows 10

**Comment by Njanderson** [comment]
Lemme give this a look - I do need to do some refinement of the battery display.

**Comment by letmaik** [comment]
WSL 2 will probably have better support for this but even if not, I think simply manually hiding the battery display as @eduncan911 is good and easy enough. You can put that into the remote machine configuration (not user configuration) so that it's only hidden for WSL. I think this is a non-issue. Everyone happy closing this?

**Comment by Njanderson** [comment]
I'm moving to a hasBattery based system where it won't show battery is systeminformation doesn't think you have one. 

If this doesn't solve your issue, I'm happy to re-visit this.
